name: VPS CI

on:
  push:
    branches:
      - main

jobs:
  vps:  
    runs-on: ubuntu-latest
    name: Server
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull code from github
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |                  
            ROOT_DIR="${{ secrets.ROOT_DIR }}"
            echo "$ROOT_DIR"
            echo "----"
            echo "[+] Git pull"
            cd "$ROOT_DIR"
            git pull
